<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AssessmentSeeder extends Seeder
{
    /**
     * Seed the assessment table with the two assessments from dolphin_4 database
     */
    public function run(): void
    {
        // Clear existing data (using delete instead of truncate due to foreign keys)
        DB::table('assessment_responses')->delete();
        DB::table('assessment')->delete();

        // Assessment 1: Page One - How others expect you to be
        DB::table('assessment')->insert([
            'id' => 1,
            'title' => 'On this first page, please select the words below that describe how other people expect you to be in most daily situations.',
            'description' => 'The words may not describe you, but they describe how other people expect you to be or act. When selecting words for each of the two different questions, please be open and honest. If you encounter an unfamiliar word, please do not search for its meaning and do not ask anyone. Instead, use your best judgment.',
            'form_definition' => json_encode([
                "Relaxed",
                "Persuasive",
                "Stable",
                "Charismatic",
                "Individualistic",
                "Optimistic",
                "Assertive",
                "Worrying",
                "Cautious",
                "Patient",
                "Audacious",
                "Captivating",
                "Conforming",
                "Methodical",
                "Serious",
                "Outgoing",
                "Meek",
                "Volatile",
                "Passive",
                "Reserved",
                "Thorough",
                "Arbitrary",
                "Disorganized",
                "Deliberate",
                "Friendly",
                "Frank",
                "Fast-Paced",
                "Intense",
                "Humble",
                "Unrestrained",
                "Competitive",
                "Docile",
                "Restless",
                "Dutiful",
                "Independent",
                "Quiet",
                "Confident",
                "Careful",
                "Harmonious",
                "Gregarious",
                "Driving",
                "Undisciplined",
                "Resourceful",
                "Non-Conforming",
                "Rebellious",
                "Conventional",
                "Enthusiastic",
                "Polite",
                "Sociable",
                "Unconventional",
                "Loyal",
                "Daring",
                "Constrained",
                "Silent",
                "Submissive",
                "Accurate",
                "High-Strung",
                "Calm",
                "Flexible",
                "Unstructured",
                "Thoughtful",
                "Informal",
                "Casual",
                "Neat",
                "Reflective",
                "Accommodating",
                "Demanding",
                "Tranquil",
                "Meticulous",
                "Stimulating",
                "Tense",
                "Disciplined",
                "Inflexible",
                "Consistent",
                "Uninhibited",
                "Logical",
                "Introspective",
                "Conscientious",
                "Forceful",
                "Shy",
                "Fussy",
                "Precise",
                "Quick",
                "Deeply Reserved",
                "Formal",
                "Respectful",
                "Organized",
                "Sophisticated",
                "Persistent",
                "Timid",
                "Responsive",
                "Self-Starter",
                "Unassuming",
                "Agreeable"
            ]),
            'created_at' => '2025-10-03 00:05:46',
            'updated_at' => '2025-10-03 00:05:46',
        ]);

        // Assessment 2: Page Two - The real you
        DB::table('assessment')->insert([
            'id' => 2,
            'title' => 'Page Two - From the list of words on this second page, please select the words that best describe you - the real you.',
            'description' => 'The words may not describe you, but they describe how other people expect you to be or act. When selecting words for each of the two different questions, please be open and honest. If you encounter an unfamiliar word, please do not search for its meaning and do not ask anyone. Instead, use your best judgment.',
            'form_definition' => json_encode([
                "Relaxed",
                "Persuasive",
                "Stable",
                "Charismatic",
                "Individualistic",
                "Optimistic",
                "Assertive",
                "Worrying",
                "Cautious",
                "Patient",
                "Audacious",
                "Captivating",
                "Conforming",
                "Methodical",
                "Serious",
                "Outgoing",
                "Meek",
                "Volatile",
                "Passive",
                "Reserved",
                "Thorough",
                "Arbitrary",
                "Disorganized",
                "Deliberate",
                "Friendly",
                "Frank",
                "Fast-Paced",
                "Intense",
                "Humble",
                "Unrestrained",
                "Competitive",
                "Docile",
                "Restless",
                "Dutiful",
                "Independent",
                "Quiet",
                "Confident",
                "Careful",
                "Harmonious",
                "Gregarious",
                "Driving",
                "Undisciplined",
                "Resourceful",
                "Non-Conforming",
                "Rebellious",
                "Conventional",
                "Enthusiastic",
                "Polite",
                "Sociable",
                "Unconventional",
                "Loyal",
                "Daring",
                "Constrained",
                "Silent",
                "Submissive",
                "Accurate",
                "High-Strung",
                "Calm",
                "Flexible",
                "Unstructured",
                "Thoughtful",
                "Informal",
                "Casual",
                "Neat",
                "Reflective",
                "Accommodating",
                "Demanding",
                "Tranquil",
                "Meticulous",
                "Stimulating",
                "Tense",
                "Disciplined",
                "Inflexible",
                "Consistent",
                "Uninhibited",
                "Logical",
                "Introspective",
                "Conscientious",
                "Forceful",
                "Shy",
                "Fussy",
                "Precise",
                "Quick",
                "Deeply Reserved",
                "Formal",
                "Respectful",
                "Organized",
                "Sophisticated",
                "Persistent",
                "Timid",
                "Responsive",
                "Self-Starter",
                "Unassuming",
                "Agreeable"
            ]),
            'created_at' => '2025-10-03 00:05:46',
            'updated_at' => '2025-10-03 00:05:46',
        ]);

        $this->command->info('Assessment table seeded with 2 assessments.');
    }
}
